version: '3.8'

services:
  web-app:
    build: .
    container_name: mi-contenedor-compose
    ports:
      - "8080:5000"
    environment:
      - USER_NAME=Aprendiz DevOps
    volumes:
      - .:/app
